language: csharp
solution: ChatUserApplication.sln
mono: none
dotnet: 1.0.1
dist: trusty
install:
  - nuget restore ChatUserApplication.sln
script:
  - xbuild /p:Configuration=Release ChatUserApplication.sln